LinkLuaModifier( "modifier_ball_catching_debuff", "modifiers/ball_catching_debuff.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ball_catching_disable", "modifiers/ball_catching_disable.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_clockcog_slow", "modifiers/clockcog_slow.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_demonic_sprint", "modifiers/demonic_sprint.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_force_normal_ball_collision", "modifiers/force_normal_ball_collision.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_goalspeed", "modifiers/goalspeed.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_invisibility", "modifiers/invisibility.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_manareg", "modifiers/manareg.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_metamorphosis", "modifiers/metamorphosis.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_mod_ball_slow", "modifiers/mod_ball_slow.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_unlimited_casting", "modifiers/modifier_unlimited_casting.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_newsprint", "modifiers/newsprint.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_night_speed", "modifiers/night_speed.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ninjainvis", "modifiers/ninjainvis.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_root_and_silence", "modifiers/root_and_silence.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_root_full", "modifiers/root_full.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_self_root", "modifiers/self_root.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shukuchi", "modifiers/shukuchi.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_unstuckmec", "modifiers/unstuckmec.lua", LUA_MODIFIER_MOTION_NONE )

if IsClient() then end
